/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGCSHARP
#define SWIGCSHARP
#endif



#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing C# exceptions from C/C++. There are two types: 
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
  SWIG_CSharpApplicationException,
  SWIG_CSharpArithmeticException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpInvalidCastException,
  SWIG_CSharpInvalidOperationException,
  SWIG_CSharpIOException,
  SWIG_CSharpNullReferenceException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpOverflowException,
  SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
  SWIG_CSharpArgumentException,
  SWIG_CSharpArgumentNullException,
  SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);
typedef void (SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
  SWIG_CSharpExceptionArgumentCodes code;
  SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpApplicationException, NULL },
  { SWIG_CSharpArithmeticException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpInvalidCastException, NULL },
  { SWIG_CSharpInvalidOperationException, NULL },
  { SWIG_CSharpIOException, NULL },
  { SWIG_CSharpNullReferenceException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpOverflowException, NULL },
  { SWIG_CSharpSystemException, NULL }
};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
  { SWIG_CSharpArgumentException, NULL },
  { SWIG_CSharpArgumentNullException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL }
};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpException_t)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name) {
  SWIG_CSharpExceptionArgumentCallback_t callback = SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions_argument)/sizeof(SWIG_CSharpExceptionArgument_t)) {
    callback = SWIG_csharp_exceptions_argument[code].callback;
  }
  callback(msg, param_name);
}


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_delivery_model(
                                                SWIG_CSharpExceptionCallback_t applicationCallback,
                                                SWIG_CSharpExceptionCallback_t arithmeticCallback,
                                                SWIG_CSharpExceptionCallback_t divideByZeroCallback, 
                                                SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, 
                                                SWIG_CSharpExceptionCallback_t invalidCastCallback,
                                                SWIG_CSharpExceptionCallback_t invalidOperationCallback,
                                                SWIG_CSharpExceptionCallback_t ioCallback,
                                                SWIG_CSharpExceptionCallback_t nullReferenceCallback,
                                                SWIG_CSharpExceptionCallback_t outOfMemoryCallback, 
                                                SWIG_CSharpExceptionCallback_t overflowCallback, 
                                                SWIG_CSharpExceptionCallback_t systemCallback) {
  SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
  SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_delivery_model(
                                                SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_delivery_model(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } else


#include <typeinfo>
#include <stdexcept>


#include <vector>
#include <algorithm>
#include <stdexcept>


/* 在包装代码中包含头文件 */
#include "model.h"
#include "order.h"
#include "point.h"
#include "rider.h"
#include "constant.h"
#include "algorithm.h"

SWIGINTERN std::vector< Rider > *new_std_vector_Sl_Rider_Sg___SWIG_2(int capacity){
        std::vector< Rider >* pv = 0;
        if (capacity >= 0) {
          pv = new std::vector< Rider >();
          pv->reserve(capacity);
       } else {
          throw std::out_of_range("capacity");
       }
       return pv;
      }
SWIGINTERN Rider std_vector_Sl_Rider_Sg__getitemcopy(std::vector< Rider > *self,int index){
        if (index>=0 && index<(int)self->size())
          return (*self)[index];
        else
          throw std::out_of_range("index");
      }
SWIGINTERN std::vector< Rider >::value_type const &std_vector_Sl_Rider_Sg__getitem(std::vector< Rider > *self,int index){
        if (index>=0 && index<(int)self->size())
          return (*self)[index];
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_Rider_Sg__setitem(std::vector< Rider > *self,int index,Rider const &val){
        if (index>=0 && index<(int)self->size())
          (*self)[index] = val;
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_Rider_Sg__AddRange(std::vector< Rider > *self,std::vector< Rider > const &values){
        self->insert(self->end(), values.begin(), values.end());
      }
SWIGINTERN std::vector< Rider > *std_vector_Sl_Rider_Sg__GetRange(std::vector< Rider > *self,int index,int count){
        if (index < 0)
          throw std::out_of_range("index");
        if (count < 0)
          throw std::out_of_range("count");
        if (index >= (int)self->size()+1 || index+count > (int)self->size())
          throw std::invalid_argument("invalid range");
        return new std::vector< Rider >(self->begin()+index, self->begin()+index+count);
      }
SWIGINTERN void std_vector_Sl_Rider_Sg__Insert(std::vector< Rider > *self,int index,Rider const &x){
        if (index>=0 && index<(int)self->size()+1)
          self->insert(self->begin()+index, x);
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_Rider_Sg__InsertRange(std::vector< Rider > *self,int index,std::vector< Rider > const &values){
        if (index>=0 && index<(int)self->size()+1)
          self->insert(self->begin()+index, values.begin(), values.end());
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_Rider_Sg__RemoveAt(std::vector< Rider > *self,int index){
        if (index>=0 && index<(int)self->size())
          self->erase(self->begin() + index);
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_Rider_Sg__RemoveRange(std::vector< Rider > *self,int index,int count){
        if (index < 0)
          throw std::out_of_range("index");
        if (count < 0)
          throw std::out_of_range("count");
        if (index >= (int)self->size()+1 || index+count > (int)self->size())
          throw std::invalid_argument("invalid range");
        self->erase(self->begin()+index, self->begin()+index+count);
      }
SWIGINTERN std::vector< Rider > *std_vector_Sl_Rider_Sg__Repeat(Rider const &value,int count){
        if (count < 0)
          throw std::out_of_range("count");
        return new std::vector< Rider >(count, value);
      }
SWIGINTERN void std_vector_Sl_Rider_Sg__Reverse__SWIG_0(std::vector< Rider > *self){
        std::reverse(self->begin(), self->end());
      }
SWIGINTERN void std_vector_Sl_Rider_Sg__Reverse__SWIG_1(std::vector< Rider > *self,int index,int count){
        if (index < 0)
          throw std::out_of_range("index");
        if (count < 0)
          throw std::out_of_range("count");
        if (index >= (int)self->size()+1 || index+count > (int)self->size())
          throw std::invalid_argument("invalid range");
        std::reverse(self->begin()+index, self->begin()+index+count);
      }
SWIGINTERN void std_vector_Sl_Rider_Sg__SetRange(std::vector< Rider > *self,int index,std::vector< Rider > const &values){
        if (index < 0)
          throw std::out_of_range("index");
        if (index+values.size() > self->size())
          throw std::out_of_range("index");
        std::copy(values.begin(), values.end(), self->begin()+index);
      }
SWIGINTERN std::vector< int > *new_std_vector_Sl_int_Sg___SWIG_2(int capacity){
        std::vector< int >* pv = 0;
        if (capacity >= 0) {
          pv = new std::vector< int >();
          pv->reserve(capacity);
       } else {
          throw std::out_of_range("capacity");
       }
       return pv;
      }
SWIGINTERN int std_vector_Sl_int_Sg__getitemcopy(std::vector< int > *self,int index){
        if (index>=0 && index<(int)self->size())
          return (*self)[index];
        else
          throw std::out_of_range("index");
      }
SWIGINTERN std::vector< int >::value_type const &std_vector_Sl_int_Sg__getitem(std::vector< int > *self,int index){
        if (index>=0 && index<(int)self->size())
          return (*self)[index];
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_int_Sg__setitem(std::vector< int > *self,int index,int const &val){
        if (index>=0 && index<(int)self->size())
          (*self)[index] = val;
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_int_Sg__AddRange(std::vector< int > *self,std::vector< int > const &values){
        self->insert(self->end(), values.begin(), values.end());
      }
SWIGINTERN std::vector< int > *std_vector_Sl_int_Sg__GetRange(std::vector< int > *self,int index,int count){
        if (index < 0)
          throw std::out_of_range("index");
        if (count < 0)
          throw std::out_of_range("count");
        if (index >= (int)self->size()+1 || index+count > (int)self->size())
          throw std::invalid_argument("invalid range");
        return new std::vector< int >(self->begin()+index, self->begin()+index+count);
      }
SWIGINTERN void std_vector_Sl_int_Sg__Insert(std::vector< int > *self,int index,int const &x){
        if (index>=0 && index<(int)self->size()+1)
          self->insert(self->begin()+index, x);
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_int_Sg__InsertRange(std::vector< int > *self,int index,std::vector< int > const &values){
        if (index>=0 && index<(int)self->size()+1)
          self->insert(self->begin()+index, values.begin(), values.end());
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_int_Sg__RemoveAt(std::vector< int > *self,int index){
        if (index>=0 && index<(int)self->size())
          self->erase(self->begin() + index);
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_int_Sg__RemoveRange(std::vector< int > *self,int index,int count){
        if (index < 0)
          throw std::out_of_range("index");
        if (count < 0)
          throw std::out_of_range("count");
        if (index >= (int)self->size()+1 || index+count > (int)self->size())
          throw std::invalid_argument("invalid range");
        self->erase(self->begin()+index, self->begin()+index+count);
      }
SWIGINTERN std::vector< int > *std_vector_Sl_int_Sg__Repeat(int const &value,int count){
        if (count < 0)
          throw std::out_of_range("count");
        return new std::vector< int >(count, value);
      }
SWIGINTERN void std_vector_Sl_int_Sg__Reverse__SWIG_0(std::vector< int > *self){
        std::reverse(self->begin(), self->end());
      }
SWIGINTERN void std_vector_Sl_int_Sg__Reverse__SWIG_1(std::vector< int > *self,int index,int count){
        if (index < 0)
          throw std::out_of_range("index");
        if (count < 0)
          throw std::out_of_range("count");
        if (index >= (int)self->size()+1 || index+count > (int)self->size())
          throw std::invalid_argument("invalid range");
        std::reverse(self->begin()+index, self->begin()+index+count);
      }
SWIGINTERN void std_vector_Sl_int_Sg__SetRange(std::vector< int > *self,int index,std::vector< int > const &values){
        if (index < 0)
          throw std::out_of_range("index");
        if (index+values.size() > self->size())
          throw std::out_of_range("index");
        std::copy(values.begin(), values.end(), self->begin()+index);
      }
SWIGINTERN bool std_vector_Sl_int_Sg__Contains(std::vector< int > *self,int const &value){
        return std::find(self->begin(), self->end(), value) != self->end();
      }
SWIGINTERN int std_vector_Sl_int_Sg__IndexOf(std::vector< int > *self,int const &value){
        int index = -1;
        std::vector< int >::iterator it = std::find(self->begin(), self->end(), value);
        if (it != self->end())
          index = (int)(it - self->begin());
        return index;
      }
SWIGINTERN int std_vector_Sl_int_Sg__LastIndexOf(std::vector< int > *self,int const &value){
        int index = -1;
        std::vector< int >::reverse_iterator rit = std::find(self->rbegin(), self->rend(), value);
        if (rit != self->rend())
          index = (int)(self->rend() - 1 - rit);
        return index;
      }
SWIGINTERN bool std_vector_Sl_int_Sg__Remove(std::vector< int > *self,int const &value){
        std::vector< int >::iterator it = std::find(self->begin(), self->end(), value);
        if (it != self->end()) {
          self->erase(it);
          return true;
        }
        return false;
      }
SWIGINTERN std::vector< Order > *new_std_vector_Sl_Order_Sg___SWIG_2(int capacity){
        std::vector< Order >* pv = 0;
        if (capacity >= 0) {
          pv = new std::vector< Order >();
          pv->reserve(capacity);
       } else {
          throw std::out_of_range("capacity");
       }
       return pv;
      }
SWIGINTERN Order std_vector_Sl_Order_Sg__getitemcopy(std::vector< Order > *self,int index){
        if (index>=0 && index<(int)self->size())
          return (*self)[index];
        else
          throw std::out_of_range("index");
      }
SWIGINTERN std::vector< Order >::value_type const &std_vector_Sl_Order_Sg__getitem(std::vector< Order > *self,int index){
        if (index>=0 && index<(int)self->size())
          return (*self)[index];
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_Order_Sg__setitem(std::vector< Order > *self,int index,Order const &val){
        if (index>=0 && index<(int)self->size())
          (*self)[index] = val;
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_Order_Sg__AddRange(std::vector< Order > *self,std::vector< Order > const &values){
        self->insert(self->end(), values.begin(), values.end());
      }
SWIGINTERN std::vector< Order > *std_vector_Sl_Order_Sg__GetRange(std::vector< Order > *self,int index,int count){
        if (index < 0)
          throw std::out_of_range("index");
        if (count < 0)
          throw std::out_of_range("count");
        if (index >= (int)self->size()+1 || index+count > (int)self->size())
          throw std::invalid_argument("invalid range");
        return new std::vector< Order >(self->begin()+index, self->begin()+index+count);
      }
SWIGINTERN void std_vector_Sl_Order_Sg__Insert(std::vector< Order > *self,int index,Order const &x){
        if (index>=0 && index<(int)self->size()+1)
          self->insert(self->begin()+index, x);
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_Order_Sg__InsertRange(std::vector< Order > *self,int index,std::vector< Order > const &values){
        if (index>=0 && index<(int)self->size()+1)
          self->insert(self->begin()+index, values.begin(), values.end());
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_Order_Sg__RemoveAt(std::vector< Order > *self,int index){
        if (index>=0 && index<(int)self->size())
          self->erase(self->begin() + index);
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_Order_Sg__RemoveRange(std::vector< Order > *self,int index,int count){
        if (index < 0)
          throw std::out_of_range("index");
        if (count < 0)
          throw std::out_of_range("count");
        if (index >= (int)self->size()+1 || index+count > (int)self->size())
          throw std::invalid_argument("invalid range");
        self->erase(self->begin()+index, self->begin()+index+count);
      }
SWIGINTERN std::vector< Order > *std_vector_Sl_Order_Sg__Repeat(Order const &value,int count){
        if (count < 0)
          throw std::out_of_range("count");
        return new std::vector< Order >(count, value);
      }
SWIGINTERN void std_vector_Sl_Order_Sg__Reverse__SWIG_0(std::vector< Order > *self){
        std::reverse(self->begin(), self->end());
      }
SWIGINTERN void std_vector_Sl_Order_Sg__Reverse__SWIG_1(std::vector< Order > *self,int index,int count){
        if (index < 0)
          throw std::out_of_range("index");
        if (count < 0)
          throw std::out_of_range("count");
        if (index >= (int)self->size()+1 || index+count > (int)self->size())
          throw std::invalid_argument("invalid range");
        std::reverse(self->begin()+index, self->begin()+index+count);
      }
SWIGINTERN void std_vector_Sl_Order_Sg__SetRange(std::vector< Order > *self,int index,std::vector< Order > const &values){
        if (index < 0)
          throw std::out_of_range("index");
        if (index+values.size() > self->size())
          throw std::out_of_range("index");
        std::copy(values.begin(), values.end(), self->begin()+index);
      }
SWIGINTERN std::vector< Point > *new_std_vector_Sl_Point_Sg___SWIG_2(int capacity){
        std::vector< Point >* pv = 0;
        if (capacity >= 0) {
          pv = new std::vector< Point >();
          pv->reserve(capacity);
       } else {
          throw std::out_of_range("capacity");
       }
       return pv;
      }
SWIGINTERN Point std_vector_Sl_Point_Sg__getitemcopy(std::vector< Point > *self,int index){
        if (index>=0 && index<(int)self->size())
          return (*self)[index];
        else
          throw std::out_of_range("index");
      }
SWIGINTERN std::vector< Point >::value_type const &std_vector_Sl_Point_Sg__getitem(std::vector< Point > *self,int index){
        if (index>=0 && index<(int)self->size())
          return (*self)[index];
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_Point_Sg__setitem(std::vector< Point > *self,int index,Point const &val){
        if (index>=0 && index<(int)self->size())
          (*self)[index] = val;
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_Point_Sg__AddRange(std::vector< Point > *self,std::vector< Point > const &values){
        self->insert(self->end(), values.begin(), values.end());
      }
SWIGINTERN std::vector< Point > *std_vector_Sl_Point_Sg__GetRange(std::vector< Point > *self,int index,int count){
        if (index < 0)
          throw std::out_of_range("index");
        if (count < 0)
          throw std::out_of_range("count");
        if (index >= (int)self->size()+1 || index+count > (int)self->size())
          throw std::invalid_argument("invalid range");
        return new std::vector< Point >(self->begin()+index, self->begin()+index+count);
      }
SWIGINTERN void std_vector_Sl_Point_Sg__Insert(std::vector< Point > *self,int index,Point const &x){
        if (index>=0 && index<(int)self->size()+1)
          self->insert(self->begin()+index, x);
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_Point_Sg__InsertRange(std::vector< Point > *self,int index,std::vector< Point > const &values){
        if (index>=0 && index<(int)self->size()+1)
          self->insert(self->begin()+index, values.begin(), values.end());
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_Point_Sg__RemoveAt(std::vector< Point > *self,int index){
        if (index>=0 && index<(int)self->size())
          self->erase(self->begin() + index);
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_Point_Sg__RemoveRange(std::vector< Point > *self,int index,int count){
        if (index < 0)
          throw std::out_of_range("index");
        if (count < 0)
          throw std::out_of_range("count");
        if (index >= (int)self->size()+1 || index+count > (int)self->size())
          throw std::invalid_argument("invalid range");
        self->erase(self->begin()+index, self->begin()+index+count);
      }
SWIGINTERN std::vector< Point > *std_vector_Sl_Point_Sg__Repeat(Point const &value,int count){
        if (count < 0)
          throw std::out_of_range("count");
        return new std::vector< Point >(count, value);
      }
SWIGINTERN void std_vector_Sl_Point_Sg__Reverse__SWIG_0(std::vector< Point > *self){
        std::reverse(self->begin(), self->end());
      }
SWIGINTERN void std_vector_Sl_Point_Sg__Reverse__SWIG_1(std::vector< Point > *self,int index,int count){
        if (index < 0)
          throw std::out_of_range("index");
        if (count < 0)
          throw std::out_of_range("count");
        if (index >= (int)self->size()+1 || index+count > (int)self->size())
          throw std::invalid_argument("invalid range");
        std::reverse(self->begin()+index, self->begin()+index+count);
      }
SWIGINTERN void std_vector_Sl_Point_Sg__SetRange(std::vector< Point > *self,int index,std::vector< Point > const &values){
        if (index < 0)
          throw std::out_of_range("index");
        if (index+values.size() > self->size())
          throw std::out_of_range("index");
        std::copy(values.begin(), values.end(), self->begin()+index);
      }

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void * SWIGSTDCALL CSharp_new_Model(void * jarg1) {
  void * jresult ;
  Point arg1 ;
  Point *argp1 ;
  Model *result = 0 ;
  
  argp1 = (Point *)jarg1; 
  if (!argp1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null Point", 0);
    return 0;
  }
  arg1 = *argp1; 
  result = (Model *)new Model(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Model_AddOrder__SWIG_0(void * jarg1, void * jarg2) {
  Model *arg1 = (Model *) 0 ;
  Order arg2 ;
  Order *argp2 ;
  
  arg1 = (Model *)jarg1; 
  argp2 = (Order *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null Order", 0);
    return ;
  }
  arg2 = *argp2; 
  (arg1)->AddOrder(arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_Model_AddOrder__SWIG_1(void * jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, int jarg7) {
  Model *arg1 = (Model *) 0 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  int arg5 ;
  int arg6 ;
  int arg7 ;
  
  arg1 = (Model *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  arg5 = (int)jarg5; 
  arg6 = (int)jarg6; 
  arg7 = (int)jarg7; 
  (arg1)->AddOrder(arg2,arg3,arg4,arg5,arg6,arg7);
}


SWIGEXPORT void SWIGSTDCALL CSharp_Model_Step(void * jarg1) {
  Model *arg1 = (Model *) 0 ;
  
  arg1 = (Model *)jarg1; 
  (arg1)->Step();
}


SWIGEXPORT int SWIGSTDCALL CSharp_Model_num_all(void * jarg1) {
  int jresult ;
  Model *arg1 = (Model *) 0 ;
  int result;
  
  arg1 = (Model *)jarg1; 
  result = (int)((Model const *)arg1)->num_all();
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_Model_num_finished(void * jarg1) {
  int jresult ;
  Model *arg1 = (Model *) 0 ;
  int result;
  
  arg1 = (Model *)jarg1; 
  result = (int)((Model const *)arg1)->num_finished();
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_Model_num_outdate(void * jarg1) {
  int jresult ;
  Model *arg1 = (Model *) 0 ;
  int result;
  
  arg1 = (Model *)jarg1; 
  result = (int)((Model const *)arg1)->num_outdate();
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_Model_money(void * jarg1) {
  int jresult ;
  Model *arg1 = (Model *) 0 ;
  int result;
  
  arg1 = (Model *)jarg1; 
  result = (int)((Model const *)arg1)->money();
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_Model_time(void * jarg1) {
  int jresult ;
  Model *arg1 = (Model *) 0 ;
  int result;
  
  arg1 = (Model *)jarg1; 
  result = (int)((Model const *)arg1)->time();
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_Model_statu(void * jarg1) {
  int jresult ;
  Model *arg1 = (Model *) 0 ;
  ProgramStatus result;
  
  arg1 = (Model *)jarg1; 
  result = (ProgramStatus)((Model const *)arg1)->statu();
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Model_riders_set(void * jarg1, void * jarg2) {
  Model *arg1 = (Model *) 0 ;
  std::vector< Rider > *arg2 = (std::vector< Rider > *) 0 ;
  
  arg1 = (Model *)jarg1; 
  arg2 = (std::vector< Rider > *)jarg2; 
  if (arg1) (arg1)->riders = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Model_riders_get(void * jarg1) {
  void * jresult ;
  Model *arg1 = (Model *) 0 ;
  std::vector< Rider > *result = 0 ;
  
  arg1 = (Model *)jarg1; 
  result = (std::vector< Rider > *)& ((arg1)->riders);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_Model(void * jarg1) {
  Model *arg1 = (Model *) 0 ;
  
  arg1 = (Model *)jarg1; 
  delete arg1;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Order_id_get(void * jarg1) {
  unsigned int jresult ;
  Order *arg1 = (Order *) 0 ;
  unsigned int result;
  
  arg1 = (Order *)jarg1; 
  result = (unsigned int)(unsigned int) ((arg1)->id);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Order_restaurant_get(void * jarg1) {
  void * jresult ;
  Order *arg1 = (Order *) 0 ;
  Point *result = 0 ;
  
  arg1 = (Order *)jarg1; 
  result = (Point *)& ((arg1)->restaurant);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Order_dinner_get(void * jarg1) {
  void * jresult ;
  Order *arg1 = (Order *) 0 ;
  Point *result = 0 ;
  
  arg1 = (Order *)jarg1; 
  result = (Point *)& ((arg1)->dinner);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Order_time_get(void * jarg1) {
  unsigned int jresult ;
  Order *arg1 = (Order *) 0 ;
  unsigned int result;
  
  arg1 = (Order *)jarg1; 
  result = (unsigned int)(unsigned int) ((arg1)->time);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_Order__SWIG_0() {
  void * jresult ;
  Order *result = 0 ;
  
  result = (Order *)new Order();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_Order__SWIG_1(unsigned int jarg1) {
  void * jresult ;
  unsigned int arg1 ;
  Order *result = 0 ;
  
  arg1 = (unsigned int)jarg1; 
  result = (Order *)new Order(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_Order__SWIG_2(unsigned int jarg1, void * jarg2, void * jarg3, unsigned int jarg4) {
  void * jresult ;
  unsigned int arg1 ;
  Point arg2 ;
  Point arg3 ;
  unsigned int arg4 ;
  Point const *argp2 ;
  Point const *argp3 ;
  Order *result = 0 ;
  
  arg1 = (unsigned int)jarg1; 
  argp2 = (Point *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null Point const", 0);
    return 0;
  }
  arg2 = *argp2; 
  argp3 = (Point *)jarg3; 
  if (!argp3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null Point const", 0);
    return 0;
  }
  arg3 = *argp3; 
  arg4 = (unsigned int)jarg4; 
  result = (Order *)new Order(arg1,arg2,arg3,arg4);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_Order(void * jarg1) {
  Order *arg1 = (Order *) 0 ;
  
  arg1 = (Order *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Point_x_set(void * jarg1, int jarg2) {
  Point *arg1 = (Point *) 0 ;
  int arg2 ;
  
  arg1 = (Point *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->x = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_Point_x_get(void * jarg1) {
  int jresult ;
  Point *arg1 = (Point *) 0 ;
  int result;
  
  arg1 = (Point *)jarg1; 
  result = (int) ((arg1)->x);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Point_y_set(void * jarg1, int jarg2) {
  Point *arg1 = (Point *) 0 ;
  int arg2 ;
  
  arg1 = (Point *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->y = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_Point_y_get(void * jarg1) {
  int jresult ;
  Point *arg1 = (Point *) 0 ;
  int result;
  
  arg1 = (Point *)jarg1; 
  result = (int) ((arg1)->y);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Point_type_set(void * jarg1, int jarg2) {
  Point *arg1 = (Point *) 0 ;
  PointType arg2 ;
  
  arg1 = (Point *)jarg1; 
  arg2 = (PointType)jarg2; 
  if (arg1) (arg1)->type = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_Point_type_get(void * jarg1) {
  int jresult ;
  Point *arg1 = (Point *) 0 ;
  PointType result;
  
  arg1 = (Point *)jarg1; 
  result = (PointType) ((arg1)->type);
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Point_order_id_set(void * jarg1, unsigned int jarg2) {
  Point *arg1 = (Point *) 0 ;
  unsigned int arg2 ;
  
  arg1 = (Point *)jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->order_id = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Point_order_id_get(void * jarg1) {
  unsigned int jresult ;
  Point *arg1 = (Point *) 0 ;
  unsigned int result;
  
  arg1 = (Point *)jarg1; 
  result = (unsigned int) ((arg1)->order_id);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_Point__SWIG_0() {
  void * jresult ;
  Point *result = 0 ;
  
  result = (Point *)new Point();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_Point__SWIG_1(int jarg1, int jarg2) {
  void * jresult ;
  int arg1 ;
  int arg2 ;
  Point *result = 0 ;
  
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  result = (Point *)new Point(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_Point__SWIG_2(int jarg1, int jarg2, int jarg3, unsigned int jarg4) {
  void * jresult ;
  int arg1 ;
  int arg2 ;
  PointType arg3 ;
  unsigned int arg4 ;
  Point *result = 0 ;
  
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (PointType)jarg3; 
  arg4 = (unsigned int)jarg4; 
  result = (Point *)new Point(arg1,arg2,arg3,arg4);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_Point(void * jarg1) {
  Point *arg1 = (Point *) 0 ;
  
  arg1 = (Point *)jarg1; 
  delete arg1;
}


SWIGEXPORT int SWIGSTDCALL CSharp_Point_GetDistant(void * jarg1, void * jarg2) {
  int jresult ;
  Point *arg1 = 0 ;
  Point *arg2 = 0 ;
  int result;
  
  arg1 = (Point *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Point const & type is null", 0);
    return 0;
  } 
  arg2 = (Point *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Point const & type is null", 0);
    return 0;
  } 
  result = (int)Point::GetDistant((Point const &)*arg1,(Point const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Point_IsArrive(void * jarg1, void * jarg2) {
  unsigned int jresult ;
  Point *arg1 = 0 ;
  Point *arg2 = 0 ;
  bool result;
  
  arg1 = (Point *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Point const & type is null", 0);
    return 0;
  } 
  arg2 = (Point *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Point const & type is null", 0);
    return 0;
  } 
  result = (bool)Point::IsArrive((Point const &)*arg1,(Point const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Point_Move(void * jarg1, void * jarg2) {
  void * jresult ;
  Point *arg1 = 0 ;
  Point *arg2 = 0 ;
  Point result;
  
  arg1 = (Point *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Point const & type is null", 0);
    return 0;
  } 
  arg2 = (Point *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Point const & type is null", 0);
    return 0;
  } 
  result = Point::Move((Point const &)*arg1,(Point const &)*arg2);
  jresult = new Point((const Point &)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_Rider(void * jarg1) {
  void * jresult ;
  Point arg1 ;
  Point *argp1 ;
  Rider *result = 0 ;
  
  argp1 = (Point *)jarg1; 
  if (!argp1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null Point", 0);
    return 0;
  }
  arg1 = *argp1; 
  result = (Rider *)new Rider(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_Rider(void * jarg1) {
  Rider *arg1 = (Rider *) 0 ;
  
  arg1 = (Rider *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Rider_Step(void * jarg1, unsigned int jarg2) {
  Rider *arg1 = (Rider *) 0 ;
  unsigned int arg2 ;
  
  arg1 = (Rider *)jarg1; 
  arg2 = (unsigned int)jarg2; 
  (arg1)->Step(arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_Rider_AddOrder(void * jarg1, void * jarg2) {
  Rider *arg1 = (Rider *) 0 ;
  Order arg2 ;
  Order *argp2 ;
  
  arg1 = (Rider *)jarg1; 
  argp2 = (Order *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null Order", 0);
    return ;
  }
  arg2 = *argp2; 
  (arg1)->AddOrder(arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_Rider_ChangePath(void * jarg1, void * jarg2, int jarg3) {
  Rider *arg1 = (Rider *) 0 ;
  SwigValueWrapper< std::queue< Point > > arg2 ;
  int arg3 ;
  std::queue< Point > *argp2 ;
  
  arg1 = (Rider *)jarg1; 
  argp2 = (std::queue< Point > *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null std::queue< Point >", 0);
    return ;
  }
  arg2 = *argp2; 
  arg3 = (int)jarg3; 
  (arg1)->ChangePath(arg2,arg3);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Rider_position(void * jarg1) {
  void * jresult ;
  Rider *arg1 = (Rider *) 0 ;
  Point result;
  
  arg1 = (Rider *)jarg1; 
  result = ((Rider const *)arg1)->position();
  jresult = new Point((const Point &)result); 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_Rider_illegal_orders(void * jarg1) {
  int jresult ;
  Rider *arg1 = (Rider *) 0 ;
  int result;
  
  arg1 = (Rider *)jarg1; 
  result = (int)((Rider const *)arg1)->illegal_orders();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Rider_outdate_orders(void * jarg1) {
  void * jresult ;
  Rider *arg1 = (Rider *) 0 ;
  std::vector< Order > *result = 0 ;
  
  arg1 = (Rider *)jarg1; 
  result = (std::vector< Order > *) &((Rider const *)arg1)->outdate_orders();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Rider_finished_orders(void * jarg1) {
  void * jresult ;
  Rider *arg1 = (Rider *) 0 ;
  std::vector< Order > *result = 0 ;
  
  arg1 = (Rider *)jarg1; 
  result = (std::vector< Order > *) &((Rider const *)arg1)->finished_orders();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Rider_outdate_orders_now(void * jarg1) {
  void * jresult ;
  Rider *arg1 = (Rider *) 0 ;
  std::vector< int > *result = 0 ;
  
  arg1 = (Rider *)jarg1; 
  result = (std::vector< int > *) &((Rider const *)arg1)->outdate_orders_now();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Rider_finished_orders_now(void * jarg1) {
  void * jresult ;
  Rider *arg1 = (Rider *) 0 ;
  std::vector< int > *result = 0 ;
  
  arg1 = (Rider *)jarg1; 
  result = (std::vector< int > *) &((Rider const *)arg1)->finished_orders_now();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Rider_received_orders(void * jarg1) {
  void * jresult ;
  Rider *arg1 = (Rider *) 0 ;
  std::set< Order > *result = 0 ;
  
  arg1 = (Rider *)jarg1; 
  result = (std::set< Order > *) &((Rider const *)arg1)->received_orders();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Rider_sending_orders(void * jarg1) {
  void * jresult ;
  Rider *arg1 = (Rider *) 0 ;
  std::set< Order > *result = 0 ;
  
  arg1 = (Rider *)jarg1; 
  result = (std::set< Order > *) &((Rider const *)arg1)->sending_orders();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Rider_dock_points(void * jarg1) {
  void * jresult ;
  Rider *arg1 = (Rider *) 0 ;
  std::vector< Point > *result = 0 ;
  
  arg1 = (Rider *)jarg1; 
  result = (std::vector< Point > *) &((Rider const *)arg1)->dock_points();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_Rider_all_cost(void * jarg1) {
  int jresult ;
  Rider *arg1 = (Rider *) 0 ;
  int result;
  
  arg1 = (Rider *)jarg1; 
  result = (int)((Rider const *)arg1)->all_cost();
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_X_get() {
  int jresult ;
  int result;
  
  result = (int)(int)X;
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_Y_get() {
  int jresult ;
  int result;
  
  result = (int)(int)Y;
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_INIT_MONEY_get() {
  int jresult ;
  int result;
  
  result = (int)(int)INIT_MONEY;
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_OUTDATE_TIME_get() {
  int jresult ;
  int result;
  
  result = (int)(int)OUTDATE_TIME;
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_ILLEGAL_TIME_get() {
  int jresult ;
  int result;
  
  result = (int)(int)ILLEGAL_TIME;
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Algorithm_cal_solution(void * jarg1, void * jarg2, int jarg3) {
  void * jresult ;
  Rider *arg1 = 0 ;
  Order *arg2 = 0 ;
  int arg3 ;
  std::tuple< std::queue< Point >,int > result;
  
  arg1 = (Rider *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Rider const & type is null", 0);
    return 0;
  } 
  arg2 = (Order *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Order const & type is null", 0);
    return 0;
  } 
  arg3 = (int)jarg3; 
  result = Algorithm::cal_solution((Rider const &)*arg1,(Order const &)*arg2,arg3);
  jresult = new std::tuple< std::queue< Point >,int >((const std::tuple< std::queue< Point >,int > &)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_Algorithm() {
  void * jresult ;
  Algorithm *result = 0 ;
  
  result = (Algorithm *)new Algorithm();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_Algorithm(void * jarg1) {
  Algorithm *arg1 = (Algorithm *) 0 ;
  
  arg1 = (Algorithm *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_RiderVector_Clear(void * jarg1) {
  std::vector< Rider > *arg1 = (std::vector< Rider > *) 0 ;
  
  arg1 = (std::vector< Rider > *)jarg1; 
  (arg1)->clear();
}


SWIGEXPORT void SWIGSTDCALL CSharp_RiderVector_Add(void * jarg1, void * jarg2) {
  std::vector< Rider > *arg1 = (std::vector< Rider > *) 0 ;
  Rider *arg2 = 0 ;
  
  arg1 = (std::vector< Rider > *)jarg1; 
  arg2 = (Rider *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Rider const & type is null", 0);
    return ;
  } 
  (arg1)->push_back((Rider const &)*arg2);
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_RiderVector_size(void * jarg1) {
  unsigned long jresult ;
  std::vector< Rider > *arg1 = (std::vector< Rider > *) 0 ;
  std::vector< Rider >::size_type result;
  
  arg1 = (std::vector< Rider > *)jarg1; 
  result = ((std::vector< Rider > const *)arg1)->size();
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_RiderVector_capacity(void * jarg1) {
  unsigned long jresult ;
  std::vector< Rider > *arg1 = (std::vector< Rider > *) 0 ;
  std::vector< Rider >::size_type result;
  
  arg1 = (std::vector< Rider > *)jarg1; 
  result = ((std::vector< Rider > const *)arg1)->capacity();
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_RiderVector_reserve(void * jarg1, unsigned long jarg2) {
  std::vector< Rider > *arg1 = (std::vector< Rider > *) 0 ;
  std::vector< Rider >::size_type arg2 ;
  
  arg1 = (std::vector< Rider > *)jarg1; 
  arg2 = (std::vector< Rider >::size_type)jarg2; 
  (arg1)->reserve(arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_RiderVector__SWIG_0() {
  void * jresult ;
  std::vector< Rider > *result = 0 ;
  
  result = (std::vector< Rider > *)new std::vector< Rider >();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_RiderVector__SWIG_1(void * jarg1) {
  void * jresult ;
  std::vector< Rider > *arg1 = 0 ;
  std::vector< Rider > *result = 0 ;
  
  arg1 = (std::vector< Rider > *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< Rider > const & type is null", 0);
    return 0;
  } 
  result = (std::vector< Rider > *)new std::vector< Rider >((std::vector< Rider > const &)*arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_RiderVector__SWIG_2(int jarg1) {
  void * jresult ;
  int arg1 ;
  std::vector< Rider > *result = 0 ;
  
  arg1 = (int)jarg1; 
  try {
    result = (std::vector< Rider > *)new_std_vector_Sl_Rider_Sg___SWIG_2(arg1);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_RiderVector_getitemcopy(void * jarg1, int jarg2) {
  void * jresult ;
  std::vector< Rider > *arg1 = (std::vector< Rider > *) 0 ;
  int arg2 ;
  SwigValueWrapper< Rider > result;
  
  arg1 = (std::vector< Rider > *)jarg1; 
  arg2 = (int)jarg2; 
  try {
    result = std_vector_Sl_Rider_Sg__getitemcopy(arg1,arg2);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  jresult = new Rider((const Rider &)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_RiderVector_getitem(void * jarg1, int jarg2) {
  void * jresult ;
  std::vector< Rider > *arg1 = (std::vector< Rider > *) 0 ;
  int arg2 ;
  std::vector< Rider >::value_type *result = 0 ;
  
  arg1 = (std::vector< Rider > *)jarg1; 
  arg2 = (int)jarg2; 
  try {
    result = (std::vector< Rider >::value_type *) &std_vector_Sl_Rider_Sg__getitem(arg1,arg2);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_RiderVector_setitem(void * jarg1, int jarg2, void * jarg3) {
  std::vector< Rider > *arg1 = (std::vector< Rider > *) 0 ;
  int arg2 ;
  Rider *arg3 = 0 ;
  
  arg1 = (std::vector< Rider > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (Rider *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Rider const & type is null", 0);
    return ;
  } 
  try {
    std_vector_Sl_Rider_Sg__setitem(arg1,arg2,(Rider const &)*arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_RiderVector_AddRange(void * jarg1, void * jarg2) {
  std::vector< Rider > *arg1 = (std::vector< Rider > *) 0 ;
  std::vector< Rider > *arg2 = 0 ;
  
  arg1 = (std::vector< Rider > *)jarg1; 
  arg2 = (std::vector< Rider > *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< Rider > const & type is null", 0);
    return ;
  } 
  std_vector_Sl_Rider_Sg__AddRange(arg1,(std::vector< Rider > const &)*arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_RiderVector_GetRange(void * jarg1, int jarg2, int jarg3) {
  void * jresult ;
  std::vector< Rider > *arg1 = (std::vector< Rider > *) 0 ;
  int arg2 ;
  int arg3 ;
  std::vector< Rider > *result = 0 ;
  
  arg1 = (std::vector< Rider > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  try {
    result = (std::vector< Rider > *)std_vector_Sl_Rider_Sg__GetRange(arg1,arg2,arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  } catch(std::invalid_argument &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentException, (&_e)->what(), "");
    return 0;
  }
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_RiderVector_Insert(void * jarg1, int jarg2, void * jarg3) {
  std::vector< Rider > *arg1 = (std::vector< Rider > *) 0 ;
  int arg2 ;
  Rider *arg3 = 0 ;
  
  arg1 = (std::vector< Rider > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (Rider *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Rider const & type is null", 0);
    return ;
  } 
  try {
    std_vector_Sl_Rider_Sg__Insert(arg1,arg2,(Rider const &)*arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_RiderVector_InsertRange(void * jarg1, int jarg2, void * jarg3) {
  std::vector< Rider > *arg1 = (std::vector< Rider > *) 0 ;
  int arg2 ;
  std::vector< Rider > *arg3 = 0 ;
  
  arg1 = (std::vector< Rider > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (std::vector< Rider > *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< Rider > const & type is null", 0);
    return ;
  } 
  try {
    std_vector_Sl_Rider_Sg__InsertRange(arg1,arg2,(std::vector< Rider > const &)*arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_RiderVector_RemoveAt(void * jarg1, int jarg2) {
  std::vector< Rider > *arg1 = (std::vector< Rider > *) 0 ;
  int arg2 ;
  
  arg1 = (std::vector< Rider > *)jarg1; 
  arg2 = (int)jarg2; 
  try {
    std_vector_Sl_Rider_Sg__RemoveAt(arg1,arg2);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_RiderVector_RemoveRange(void * jarg1, int jarg2, int jarg3) {
  std::vector< Rider > *arg1 = (std::vector< Rider > *) 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (std::vector< Rider > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  try {
    std_vector_Sl_Rider_Sg__RemoveRange(arg1,arg2,arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  } catch(std::invalid_argument &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentException, (&_e)->what(), "");
    return ;
  }
}


SWIGEXPORT void * SWIGSTDCALL CSharp_RiderVector_Repeat(void * jarg1, int jarg2) {
  void * jresult ;
  Rider *arg1 = 0 ;
  int arg2 ;
  std::vector< Rider > *result = 0 ;
  
  arg1 = (Rider *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Rider const & type is null", 0);
    return 0;
  } 
  arg2 = (int)jarg2; 
  try {
    result = (std::vector< Rider > *)std_vector_Sl_Rider_Sg__Repeat((Rider const &)*arg1,arg2);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_RiderVector_Reverse__SWIG_0(void * jarg1) {
  std::vector< Rider > *arg1 = (std::vector< Rider > *) 0 ;
  
  arg1 = (std::vector< Rider > *)jarg1; 
  std_vector_Sl_Rider_Sg__Reverse__SWIG_0(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_RiderVector_Reverse__SWIG_1(void * jarg1, int jarg2, int jarg3) {
  std::vector< Rider > *arg1 = (std::vector< Rider > *) 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (std::vector< Rider > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  try {
    std_vector_Sl_Rider_Sg__Reverse__SWIG_1(arg1,arg2,arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  } catch(std::invalid_argument &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentException, (&_e)->what(), "");
    return ;
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_RiderVector_SetRange(void * jarg1, int jarg2, void * jarg3) {
  std::vector< Rider > *arg1 = (std::vector< Rider > *) 0 ;
  int arg2 ;
  std::vector< Rider > *arg3 = 0 ;
  
  arg1 = (std::vector< Rider > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (std::vector< Rider > *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< Rider > const & type is null", 0);
    return ;
  } 
  try {
    std_vector_Sl_Rider_Sg__SetRange(arg1,arg2,(std::vector< Rider > const &)*arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_RiderVector(void * jarg1) {
  std::vector< Rider > *arg1 = (std::vector< Rider > *) 0 ;
  
  arg1 = (std::vector< Rider > *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_IntVector_Clear(void * jarg1) {
  std::vector< int > *arg1 = (std::vector< int > *) 0 ;
  
  arg1 = (std::vector< int > *)jarg1; 
  (arg1)->clear();
}


SWIGEXPORT void SWIGSTDCALL CSharp_IntVector_Add(void * jarg1, int jarg2) {
  std::vector< int > *arg1 = (std::vector< int > *) 0 ;
  int *arg2 = 0 ;
  int temp2 ;
  
  arg1 = (std::vector< int > *)jarg1; 
  temp2 = (int)jarg2; 
  arg2 = &temp2; 
  (arg1)->push_back((int const &)*arg2);
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_IntVector_size(void * jarg1) {
  unsigned long jresult ;
  std::vector< int > *arg1 = (std::vector< int > *) 0 ;
  std::vector< int >::size_type result;
  
  arg1 = (std::vector< int > *)jarg1; 
  result = ((std::vector< int > const *)arg1)->size();
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_IntVector_capacity(void * jarg1) {
  unsigned long jresult ;
  std::vector< int > *arg1 = (std::vector< int > *) 0 ;
  std::vector< int >::size_type result;
  
  arg1 = (std::vector< int > *)jarg1; 
  result = ((std::vector< int > const *)arg1)->capacity();
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_IntVector_reserve(void * jarg1, unsigned long jarg2) {
  std::vector< int > *arg1 = (std::vector< int > *) 0 ;
  std::vector< int >::size_type arg2 ;
  
  arg1 = (std::vector< int > *)jarg1; 
  arg2 = (std::vector< int >::size_type)jarg2; 
  (arg1)->reserve(arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_IntVector__SWIG_0() {
  void * jresult ;
  std::vector< int > *result = 0 ;
  
  result = (std::vector< int > *)new std::vector< int >();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_IntVector__SWIG_1(void * jarg1) {
  void * jresult ;
  std::vector< int > *arg1 = 0 ;
  std::vector< int > *result = 0 ;
  
  arg1 = (std::vector< int > *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< int > const & type is null", 0);
    return 0;
  } 
  result = (std::vector< int > *)new std::vector< int >((std::vector< int > const &)*arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_IntVector__SWIG_2(int jarg1) {
  void * jresult ;
  int arg1 ;
  std::vector< int > *result = 0 ;
  
  arg1 = (int)jarg1; 
  try {
    result = (std::vector< int > *)new_std_vector_Sl_int_Sg___SWIG_2(arg1);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_IntVector_getitemcopy(void * jarg1, int jarg2) {
  int jresult ;
  std::vector< int > *arg1 = (std::vector< int > *) 0 ;
  int arg2 ;
  int result;
  
  arg1 = (std::vector< int > *)jarg1; 
  arg2 = (int)jarg2; 
  try {
    result = (int)std_vector_Sl_int_Sg__getitemcopy(arg1,arg2);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_IntVector_getitem(void * jarg1, int jarg2) {
  int jresult ;
  std::vector< int > *arg1 = (std::vector< int > *) 0 ;
  int arg2 ;
  std::vector< int >::value_type *result = 0 ;
  
  arg1 = (std::vector< int > *)jarg1; 
  arg2 = (int)jarg2; 
  try {
    result = (std::vector< int >::value_type *) &std_vector_Sl_int_Sg__getitem(arg1,arg2);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  jresult = *result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_IntVector_setitem(void * jarg1, int jarg2, int jarg3) {
  std::vector< int > *arg1 = (std::vector< int > *) 0 ;
  int arg2 ;
  int *arg3 = 0 ;
  int temp3 ;
  
  arg1 = (std::vector< int > *)jarg1; 
  arg2 = (int)jarg2; 
  temp3 = (int)jarg3; 
  arg3 = &temp3; 
  try {
    std_vector_Sl_int_Sg__setitem(arg1,arg2,(int const &)*arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_IntVector_AddRange(void * jarg1, void * jarg2) {
  std::vector< int > *arg1 = (std::vector< int > *) 0 ;
  std::vector< int > *arg2 = 0 ;
  
  arg1 = (std::vector< int > *)jarg1; 
  arg2 = (std::vector< int > *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< int > const & type is null", 0);
    return ;
  } 
  std_vector_Sl_int_Sg__AddRange(arg1,(std::vector< int > const &)*arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_IntVector_GetRange(void * jarg1, int jarg2, int jarg3) {
  void * jresult ;
  std::vector< int > *arg1 = (std::vector< int > *) 0 ;
  int arg2 ;
  int arg3 ;
  std::vector< int > *result = 0 ;
  
  arg1 = (std::vector< int > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  try {
    result = (std::vector< int > *)std_vector_Sl_int_Sg__GetRange(arg1,arg2,arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  } catch(std::invalid_argument &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentException, (&_e)->what(), "");
    return 0;
  }
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_IntVector_Insert(void * jarg1, int jarg2, int jarg3) {
  std::vector< int > *arg1 = (std::vector< int > *) 0 ;
  int arg2 ;
  int *arg3 = 0 ;
  int temp3 ;
  
  arg1 = (std::vector< int > *)jarg1; 
  arg2 = (int)jarg2; 
  temp3 = (int)jarg3; 
  arg3 = &temp3; 
  try {
    std_vector_Sl_int_Sg__Insert(arg1,arg2,(int const &)*arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_IntVector_InsertRange(void * jarg1, int jarg2, void * jarg3) {
  std::vector< int > *arg1 = (std::vector< int > *) 0 ;
  int arg2 ;
  std::vector< int > *arg3 = 0 ;
  
  arg1 = (std::vector< int > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (std::vector< int > *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< int > const & type is null", 0);
    return ;
  } 
  try {
    std_vector_Sl_int_Sg__InsertRange(arg1,arg2,(std::vector< int > const &)*arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_IntVector_RemoveAt(void * jarg1, int jarg2) {
  std::vector< int > *arg1 = (std::vector< int > *) 0 ;
  int arg2 ;
  
  arg1 = (std::vector< int > *)jarg1; 
  arg2 = (int)jarg2; 
  try {
    std_vector_Sl_int_Sg__RemoveAt(arg1,arg2);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_IntVector_RemoveRange(void * jarg1, int jarg2, int jarg3) {
  std::vector< int > *arg1 = (std::vector< int > *) 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (std::vector< int > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  try {
    std_vector_Sl_int_Sg__RemoveRange(arg1,arg2,arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  } catch(std::invalid_argument &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentException, (&_e)->what(), "");
    return ;
  }
}


SWIGEXPORT void * SWIGSTDCALL CSharp_IntVector_Repeat(int jarg1, int jarg2) {
  void * jresult ;
  int *arg1 = 0 ;
  int arg2 ;
  int temp1 ;
  std::vector< int > *result = 0 ;
  
  temp1 = (int)jarg1; 
  arg1 = &temp1; 
  arg2 = (int)jarg2; 
  try {
    result = (std::vector< int > *)std_vector_Sl_int_Sg__Repeat((int const &)*arg1,arg2);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_IntVector_Reverse__SWIG_0(void * jarg1) {
  std::vector< int > *arg1 = (std::vector< int > *) 0 ;
  
  arg1 = (std::vector< int > *)jarg1; 
  std_vector_Sl_int_Sg__Reverse__SWIG_0(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_IntVector_Reverse__SWIG_1(void * jarg1, int jarg2, int jarg3) {
  std::vector< int > *arg1 = (std::vector< int > *) 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (std::vector< int > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  try {
    std_vector_Sl_int_Sg__Reverse__SWIG_1(arg1,arg2,arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  } catch(std::invalid_argument &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentException, (&_e)->what(), "");
    return ;
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_IntVector_SetRange(void * jarg1, int jarg2, void * jarg3) {
  std::vector< int > *arg1 = (std::vector< int > *) 0 ;
  int arg2 ;
  std::vector< int > *arg3 = 0 ;
  
  arg1 = (std::vector< int > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (std::vector< int > *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< int > const & type is null", 0);
    return ;
  } 
  try {
    std_vector_Sl_int_Sg__SetRange(arg1,arg2,(std::vector< int > const &)*arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_IntVector_Contains(void * jarg1, int jarg2) {
  unsigned int jresult ;
  std::vector< int > *arg1 = (std::vector< int > *) 0 ;
  int *arg2 = 0 ;
  int temp2 ;
  bool result;
  
  arg1 = (std::vector< int > *)jarg1; 
  temp2 = (int)jarg2; 
  arg2 = &temp2; 
  result = (bool)std_vector_Sl_int_Sg__Contains(arg1,(int const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_IntVector_IndexOf(void * jarg1, int jarg2) {
  int jresult ;
  std::vector< int > *arg1 = (std::vector< int > *) 0 ;
  int *arg2 = 0 ;
  int temp2 ;
  int result;
  
  arg1 = (std::vector< int > *)jarg1; 
  temp2 = (int)jarg2; 
  arg2 = &temp2; 
  result = (int)std_vector_Sl_int_Sg__IndexOf(arg1,(int const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_IntVector_LastIndexOf(void * jarg1, int jarg2) {
  int jresult ;
  std::vector< int > *arg1 = (std::vector< int > *) 0 ;
  int *arg2 = 0 ;
  int temp2 ;
  int result;
  
  arg1 = (std::vector< int > *)jarg1; 
  temp2 = (int)jarg2; 
  arg2 = &temp2; 
  result = (int)std_vector_Sl_int_Sg__LastIndexOf(arg1,(int const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_IntVector_Remove(void * jarg1, int jarg2) {
  unsigned int jresult ;
  std::vector< int > *arg1 = (std::vector< int > *) 0 ;
  int *arg2 = 0 ;
  int temp2 ;
  bool result;
  
  arg1 = (std::vector< int > *)jarg1; 
  temp2 = (int)jarg2; 
  arg2 = &temp2; 
  result = (bool)std_vector_Sl_int_Sg__Remove(arg1,(int const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_IntVector(void * jarg1) {
  std::vector< int > *arg1 = (std::vector< int > *) 0 ;
  
  arg1 = (std::vector< int > *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_OrderVector_Clear(void * jarg1) {
  std::vector< Order > *arg1 = (std::vector< Order > *) 0 ;
  
  arg1 = (std::vector< Order > *)jarg1; 
  (arg1)->clear();
}


SWIGEXPORT void SWIGSTDCALL CSharp_OrderVector_Add(void * jarg1, void * jarg2) {
  std::vector< Order > *arg1 = (std::vector< Order > *) 0 ;
  Order *arg2 = 0 ;
  
  arg1 = (std::vector< Order > *)jarg1; 
  arg2 = (Order *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Order const & type is null", 0);
    return ;
  } 
  (arg1)->push_back((Order const &)*arg2);
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_OrderVector_size(void * jarg1) {
  unsigned long jresult ;
  std::vector< Order > *arg1 = (std::vector< Order > *) 0 ;
  std::vector< Order >::size_type result;
  
  arg1 = (std::vector< Order > *)jarg1; 
  result = ((std::vector< Order > const *)arg1)->size();
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_OrderVector_capacity(void * jarg1) {
  unsigned long jresult ;
  std::vector< Order > *arg1 = (std::vector< Order > *) 0 ;
  std::vector< Order >::size_type result;
  
  arg1 = (std::vector< Order > *)jarg1; 
  result = ((std::vector< Order > const *)arg1)->capacity();
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_OrderVector_reserve(void * jarg1, unsigned long jarg2) {
  std::vector< Order > *arg1 = (std::vector< Order > *) 0 ;
  std::vector< Order >::size_type arg2 ;
  
  arg1 = (std::vector< Order > *)jarg1; 
  arg2 = (std::vector< Order >::size_type)jarg2; 
  (arg1)->reserve(arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_OrderVector__SWIG_0() {
  void * jresult ;
  std::vector< Order > *result = 0 ;
  
  result = (std::vector< Order > *)new std::vector< Order >();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_OrderVector__SWIG_1(void * jarg1) {
  void * jresult ;
  std::vector< Order > *arg1 = 0 ;
  std::vector< Order > *result = 0 ;
  
  arg1 = (std::vector< Order > *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< Order > const & type is null", 0);
    return 0;
  } 
  result = (std::vector< Order > *)new std::vector< Order >((std::vector< Order > const &)*arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_OrderVector__SWIG_2(int jarg1) {
  void * jresult ;
  int arg1 ;
  std::vector< Order > *result = 0 ;
  
  arg1 = (int)jarg1; 
  try {
    result = (std::vector< Order > *)new_std_vector_Sl_Order_Sg___SWIG_2(arg1);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_OrderVector_getitemcopy(void * jarg1, int jarg2) {
  void * jresult ;
  std::vector< Order > *arg1 = (std::vector< Order > *) 0 ;
  int arg2 ;
  Order result;
  
  arg1 = (std::vector< Order > *)jarg1; 
  arg2 = (int)jarg2; 
  try {
    result = std_vector_Sl_Order_Sg__getitemcopy(arg1,arg2);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  jresult = new Order((const Order &)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_OrderVector_getitem(void * jarg1, int jarg2) {
  void * jresult ;
  std::vector< Order > *arg1 = (std::vector< Order > *) 0 ;
  int arg2 ;
  std::vector< Order >::value_type *result = 0 ;
  
  arg1 = (std::vector< Order > *)jarg1; 
  arg2 = (int)jarg2; 
  try {
    result = (std::vector< Order >::value_type *) &std_vector_Sl_Order_Sg__getitem(arg1,arg2);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_OrderVector_setitem(void * jarg1, int jarg2, void * jarg3) {
  std::vector< Order > *arg1 = (std::vector< Order > *) 0 ;
  int arg2 ;
  Order *arg3 = 0 ;
  
  arg1 = (std::vector< Order > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (Order *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Order const & type is null", 0);
    return ;
  } 
  try {
    std_vector_Sl_Order_Sg__setitem(arg1,arg2,(Order const &)*arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_OrderVector_AddRange(void * jarg1, void * jarg2) {
  std::vector< Order > *arg1 = (std::vector< Order > *) 0 ;
  std::vector< Order > *arg2 = 0 ;
  
  arg1 = (std::vector< Order > *)jarg1; 
  arg2 = (std::vector< Order > *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< Order > const & type is null", 0);
    return ;
  } 
  std_vector_Sl_Order_Sg__AddRange(arg1,(std::vector< Order > const &)*arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_OrderVector_GetRange(void * jarg1, int jarg2, int jarg3) {
  void * jresult ;
  std::vector< Order > *arg1 = (std::vector< Order > *) 0 ;
  int arg2 ;
  int arg3 ;
  std::vector< Order > *result = 0 ;
  
  arg1 = (std::vector< Order > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  try {
    result = (std::vector< Order > *)std_vector_Sl_Order_Sg__GetRange(arg1,arg2,arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  } catch(std::invalid_argument &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentException, (&_e)->what(), "");
    return 0;
  }
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_OrderVector_Insert(void * jarg1, int jarg2, void * jarg3) {
  std::vector< Order > *arg1 = (std::vector< Order > *) 0 ;
  int arg2 ;
  Order *arg3 = 0 ;
  
  arg1 = (std::vector< Order > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (Order *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Order const & type is null", 0);
    return ;
  } 
  try {
    std_vector_Sl_Order_Sg__Insert(arg1,arg2,(Order const &)*arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_OrderVector_InsertRange(void * jarg1, int jarg2, void * jarg3) {
  std::vector< Order > *arg1 = (std::vector< Order > *) 0 ;
  int arg2 ;
  std::vector< Order > *arg3 = 0 ;
  
  arg1 = (std::vector< Order > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (std::vector< Order > *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< Order > const & type is null", 0);
    return ;
  } 
  try {
    std_vector_Sl_Order_Sg__InsertRange(arg1,arg2,(std::vector< Order > const &)*arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_OrderVector_RemoveAt(void * jarg1, int jarg2) {
  std::vector< Order > *arg1 = (std::vector< Order > *) 0 ;
  int arg2 ;
  
  arg1 = (std::vector< Order > *)jarg1; 
  arg2 = (int)jarg2; 
  try {
    std_vector_Sl_Order_Sg__RemoveAt(arg1,arg2);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_OrderVector_RemoveRange(void * jarg1, int jarg2, int jarg3) {
  std::vector< Order > *arg1 = (std::vector< Order > *) 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (std::vector< Order > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  try {
    std_vector_Sl_Order_Sg__RemoveRange(arg1,arg2,arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  } catch(std::invalid_argument &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentException, (&_e)->what(), "");
    return ;
  }
}


SWIGEXPORT void * SWIGSTDCALL CSharp_OrderVector_Repeat(void * jarg1, int jarg2) {
  void * jresult ;
  Order *arg1 = 0 ;
  int arg2 ;
  std::vector< Order > *result = 0 ;
  
  arg1 = (Order *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Order const & type is null", 0);
    return 0;
  } 
  arg2 = (int)jarg2; 
  try {
    result = (std::vector< Order > *)std_vector_Sl_Order_Sg__Repeat((Order const &)*arg1,arg2);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_OrderVector_Reverse__SWIG_0(void * jarg1) {
  std::vector< Order > *arg1 = (std::vector< Order > *) 0 ;
  
  arg1 = (std::vector< Order > *)jarg1; 
  std_vector_Sl_Order_Sg__Reverse__SWIG_0(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_OrderVector_Reverse__SWIG_1(void * jarg1, int jarg2, int jarg3) {
  std::vector< Order > *arg1 = (std::vector< Order > *) 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (std::vector< Order > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  try {
    std_vector_Sl_Order_Sg__Reverse__SWIG_1(arg1,arg2,arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  } catch(std::invalid_argument &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentException, (&_e)->what(), "");
    return ;
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_OrderVector_SetRange(void * jarg1, int jarg2, void * jarg3) {
  std::vector< Order > *arg1 = (std::vector< Order > *) 0 ;
  int arg2 ;
  std::vector< Order > *arg3 = 0 ;
  
  arg1 = (std::vector< Order > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (std::vector< Order > *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< Order > const & type is null", 0);
    return ;
  } 
  try {
    std_vector_Sl_Order_Sg__SetRange(arg1,arg2,(std::vector< Order > const &)*arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_OrderVector(void * jarg1) {
  std::vector< Order > *arg1 = (std::vector< Order > *) 0 ;
  
  arg1 = (std::vector< Order > *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_PointVector_Clear(void * jarg1) {
  std::vector< Point > *arg1 = (std::vector< Point > *) 0 ;
  
  arg1 = (std::vector< Point > *)jarg1; 
  (arg1)->clear();
}


SWIGEXPORT void SWIGSTDCALL CSharp_PointVector_Add(void * jarg1, void * jarg2) {
  std::vector< Point > *arg1 = (std::vector< Point > *) 0 ;
  Point *arg2 = 0 ;
  
  arg1 = (std::vector< Point > *)jarg1; 
  arg2 = (Point *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Point const & type is null", 0);
    return ;
  } 
  (arg1)->push_back((Point const &)*arg2);
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_PointVector_size(void * jarg1) {
  unsigned long jresult ;
  std::vector< Point > *arg1 = (std::vector< Point > *) 0 ;
  std::vector< Point >::size_type result;
  
  arg1 = (std::vector< Point > *)jarg1; 
  result = ((std::vector< Point > const *)arg1)->size();
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_PointVector_capacity(void * jarg1) {
  unsigned long jresult ;
  std::vector< Point > *arg1 = (std::vector< Point > *) 0 ;
  std::vector< Point >::size_type result;
  
  arg1 = (std::vector< Point > *)jarg1; 
  result = ((std::vector< Point > const *)arg1)->capacity();
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_PointVector_reserve(void * jarg1, unsigned long jarg2) {
  std::vector< Point > *arg1 = (std::vector< Point > *) 0 ;
  std::vector< Point >::size_type arg2 ;
  
  arg1 = (std::vector< Point > *)jarg1; 
  arg2 = (std::vector< Point >::size_type)jarg2; 
  (arg1)->reserve(arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_PointVector__SWIG_0() {
  void * jresult ;
  std::vector< Point > *result = 0 ;
  
  result = (std::vector< Point > *)new std::vector< Point >();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_PointVector__SWIG_1(void * jarg1) {
  void * jresult ;
  std::vector< Point > *arg1 = 0 ;
  std::vector< Point > *result = 0 ;
  
  arg1 = (std::vector< Point > *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< Point > const & type is null", 0);
    return 0;
  } 
  result = (std::vector< Point > *)new std::vector< Point >((std::vector< Point > const &)*arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_PointVector__SWIG_2(int jarg1) {
  void * jresult ;
  int arg1 ;
  std::vector< Point > *result = 0 ;
  
  arg1 = (int)jarg1; 
  try {
    result = (std::vector< Point > *)new_std_vector_Sl_Point_Sg___SWIG_2(arg1);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_PointVector_getitemcopy(void * jarg1, int jarg2) {
  void * jresult ;
  std::vector< Point > *arg1 = (std::vector< Point > *) 0 ;
  int arg2 ;
  Point result;
  
  arg1 = (std::vector< Point > *)jarg1; 
  arg2 = (int)jarg2; 
  try {
    result = std_vector_Sl_Point_Sg__getitemcopy(arg1,arg2);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  jresult = new Point((const Point &)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_PointVector_getitem(void * jarg1, int jarg2) {
  void * jresult ;
  std::vector< Point > *arg1 = (std::vector< Point > *) 0 ;
  int arg2 ;
  std::vector< Point >::value_type *result = 0 ;
  
  arg1 = (std::vector< Point > *)jarg1; 
  arg2 = (int)jarg2; 
  try {
    result = (std::vector< Point >::value_type *) &std_vector_Sl_Point_Sg__getitem(arg1,arg2);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_PointVector_setitem(void * jarg1, int jarg2, void * jarg3) {
  std::vector< Point > *arg1 = (std::vector< Point > *) 0 ;
  int arg2 ;
  Point *arg3 = 0 ;
  
  arg1 = (std::vector< Point > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (Point *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Point const & type is null", 0);
    return ;
  } 
  try {
    std_vector_Sl_Point_Sg__setitem(arg1,arg2,(Point const &)*arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_PointVector_AddRange(void * jarg1, void * jarg2) {
  std::vector< Point > *arg1 = (std::vector< Point > *) 0 ;
  std::vector< Point > *arg2 = 0 ;
  
  arg1 = (std::vector< Point > *)jarg1; 
  arg2 = (std::vector< Point > *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< Point > const & type is null", 0);
    return ;
  } 
  std_vector_Sl_Point_Sg__AddRange(arg1,(std::vector< Point > const &)*arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_PointVector_GetRange(void * jarg1, int jarg2, int jarg3) {
  void * jresult ;
  std::vector< Point > *arg1 = (std::vector< Point > *) 0 ;
  int arg2 ;
  int arg3 ;
  std::vector< Point > *result = 0 ;
  
  arg1 = (std::vector< Point > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  try {
    result = (std::vector< Point > *)std_vector_Sl_Point_Sg__GetRange(arg1,arg2,arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  } catch(std::invalid_argument &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentException, (&_e)->what(), "");
    return 0;
  }
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_PointVector_Insert(void * jarg1, int jarg2, void * jarg3) {
  std::vector< Point > *arg1 = (std::vector< Point > *) 0 ;
  int arg2 ;
  Point *arg3 = 0 ;
  
  arg1 = (std::vector< Point > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (Point *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Point const & type is null", 0);
    return ;
  } 
  try {
    std_vector_Sl_Point_Sg__Insert(arg1,arg2,(Point const &)*arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_PointVector_InsertRange(void * jarg1, int jarg2, void * jarg3) {
  std::vector< Point > *arg1 = (std::vector< Point > *) 0 ;
  int arg2 ;
  std::vector< Point > *arg3 = 0 ;
  
  arg1 = (std::vector< Point > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (std::vector< Point > *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< Point > const & type is null", 0);
    return ;
  } 
  try {
    std_vector_Sl_Point_Sg__InsertRange(arg1,arg2,(std::vector< Point > const &)*arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_PointVector_RemoveAt(void * jarg1, int jarg2) {
  std::vector< Point > *arg1 = (std::vector< Point > *) 0 ;
  int arg2 ;
  
  arg1 = (std::vector< Point > *)jarg1; 
  arg2 = (int)jarg2; 
  try {
    std_vector_Sl_Point_Sg__RemoveAt(arg1,arg2);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_PointVector_RemoveRange(void * jarg1, int jarg2, int jarg3) {
  std::vector< Point > *arg1 = (std::vector< Point > *) 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (std::vector< Point > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  try {
    std_vector_Sl_Point_Sg__RemoveRange(arg1,arg2,arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  } catch(std::invalid_argument &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentException, (&_e)->what(), "");
    return ;
  }
}


SWIGEXPORT void * SWIGSTDCALL CSharp_PointVector_Repeat(void * jarg1, int jarg2) {
  void * jresult ;
  Point *arg1 = 0 ;
  int arg2 ;
  std::vector< Point > *result = 0 ;
  
  arg1 = (Point *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Point const & type is null", 0);
    return 0;
  } 
  arg2 = (int)jarg2; 
  try {
    result = (std::vector< Point > *)std_vector_Sl_Point_Sg__Repeat((Point const &)*arg1,arg2);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_PointVector_Reverse__SWIG_0(void * jarg1) {
  std::vector< Point > *arg1 = (std::vector< Point > *) 0 ;
  
  arg1 = (std::vector< Point > *)jarg1; 
  std_vector_Sl_Point_Sg__Reverse__SWIG_0(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_PointVector_Reverse__SWIG_1(void * jarg1, int jarg2, int jarg3) {
  std::vector< Point > *arg1 = (std::vector< Point > *) 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (std::vector< Point > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  try {
    std_vector_Sl_Point_Sg__Reverse__SWIG_1(arg1,arg2,arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  } catch(std::invalid_argument &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentException, (&_e)->what(), "");
    return ;
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_PointVector_SetRange(void * jarg1, int jarg2, void * jarg3) {
  std::vector< Point > *arg1 = (std::vector< Point > *) 0 ;
  int arg2 ;
  std::vector< Point > *arg3 = 0 ;
  
  arg1 = (std::vector< Point > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (std::vector< Point > *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< Point > const & type is null", 0);
    return ;
  } 
  try {
    std_vector_Sl_Point_Sg__SetRange(arg1,arg2,(std::vector< Point > const &)*arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_PointVector(void * jarg1) {
  std::vector< Point > *arg1 = (std::vector< Point > *) 0 ;
  
  arg1 = (std::vector< Point > *)jarg1; 
  delete arg1;
}


#ifdef __cplusplus
}
#endif

