//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


class delivery_modelPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="SWIGRegisterExceptionCallbacks_delivery_model")]
    public static extern void SWIGRegisterExceptionCallbacks_delivery_model(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_delivery_model")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_delivery_model(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_delivery_model(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_delivery_model(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;
    private static global::System.Object exceptionsLock = null;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(exceptionsLock) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(exceptionsLock) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }

    static SWIGPendingException() {
      exceptionsLock = new global::System.Object();
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="SWIGRegisterStringCallback_delivery_model")]
    public static extern void SWIGRegisterStringCallback_delivery_model(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_delivery_model(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static delivery_modelPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_new_Model")]
  public static extern global::System.IntPtr new_Model(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Model_AddOrder__SWIG_0")]
  public static extern void Model_AddOrder__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Model_AddOrder__SWIG_1")]
  public static extern void Model_AddOrder__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, int jarg7);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Model_Step")]
  public static extern void Model_Step(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Model_num_all")]
  public static extern int Model_num_all(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Model_num_finished")]
  public static extern int Model_num_finished(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Model_num_outdate")]
  public static extern int Model_num_outdate(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Model_money")]
  public static extern int Model_money(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Model_time")]
  public static extern int Model_time(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Model_statu")]
  public static extern int Model_statu(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Model_riders_set")]
  public static extern void Model_riders_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Model_riders_get")]
  public static extern global::System.IntPtr Model_riders_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_delete_Model")]
  public static extern void delete_Model(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Order_id_get")]
  public static extern uint Order_id_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Order_restaurant_get")]
  public static extern global::System.IntPtr Order_restaurant_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Order_dinner_get")]
  public static extern global::System.IntPtr Order_dinner_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Order_time_get")]
  public static extern uint Order_time_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_new_Order__SWIG_0")]
  public static extern global::System.IntPtr new_Order__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_new_Order__SWIG_1")]
  public static extern global::System.IntPtr new_Order__SWIG_1(uint jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_new_Order__SWIG_2")]
  public static extern global::System.IntPtr new_Order__SWIG_2(uint jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, uint jarg4);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_delete_Order")]
  public static extern void delete_Order(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Point_x_set")]
  public static extern void Point_x_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Point_x_get")]
  public static extern int Point_x_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Point_y_set")]
  public static extern void Point_y_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Point_y_get")]
  public static extern int Point_y_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Point_type_set")]
  public static extern void Point_type_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Point_type_get")]
  public static extern int Point_type_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Point_order_id_set")]
  public static extern void Point_order_id_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Point_order_id_get")]
  public static extern uint Point_order_id_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_new_Point__SWIG_0")]
  public static extern global::System.IntPtr new_Point__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_new_Point__SWIG_1")]
  public static extern global::System.IntPtr new_Point__SWIG_1(int jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_new_Point__SWIG_2")]
  public static extern global::System.IntPtr new_Point__SWIG_2(int jarg1, int jarg2, int jarg3, uint jarg4);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_delete_Point")]
  public static extern void delete_Point(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Point_GetDistant")]
  public static extern int Point_GetDistant(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Point_IsArrive")]
  public static extern bool Point_IsArrive(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Point_Move")]
  public static extern global::System.IntPtr Point_Move(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_new_Rider")]
  public static extern global::System.IntPtr new_Rider(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_delete_Rider")]
  public static extern void delete_Rider(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Rider_Step")]
  public static extern void Rider_Step(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Rider_AddOrder")]
  public static extern void Rider_AddOrder(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Rider_ChangePath")]
  public static extern void Rider_ChangePath(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Rider_position")]
  public static extern global::System.IntPtr Rider_position(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Rider_illegal_orders")]
  public static extern int Rider_illegal_orders(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Rider_outdate_orders")]
  public static extern global::System.IntPtr Rider_outdate_orders(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Rider_finished_orders")]
  public static extern global::System.IntPtr Rider_finished_orders(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Rider_outdate_orders_now")]
  public static extern global::System.IntPtr Rider_outdate_orders_now(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Rider_finished_orders_now")]
  public static extern global::System.IntPtr Rider_finished_orders_now(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Rider_received_orders")]
  public static extern global::System.IntPtr Rider_received_orders(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Rider_sending_orders")]
  public static extern global::System.IntPtr Rider_sending_orders(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Rider_dock_points")]
  public static extern global::System.IntPtr Rider_dock_points(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Rider_all_cost")]
  public static extern int Rider_all_cost(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_X_get")]
  public static extern int X_get();

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Y_get")]
  public static extern int Y_get();

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_INIT_MONEY_get")]
  public static extern int INIT_MONEY_get();

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_OUTDATE_TIME_get")]
  public static extern int OUTDATE_TIME_get();

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_ILLEGAL_TIME_get")]
  public static extern int ILLEGAL_TIME_get();

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_Algorithm_cal_solution")]
  public static extern global::System.IntPtr Algorithm_cal_solution(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_new_Algorithm")]
  public static extern global::System.IntPtr new_Algorithm();

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_delete_Algorithm")]
  public static extern void delete_Algorithm(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_RiderVector_Clear")]
  public static extern void RiderVector_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_RiderVector_Add")]
  public static extern void RiderVector_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_RiderVector_size")]
  public static extern uint RiderVector_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_RiderVector_capacity")]
  public static extern uint RiderVector_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_RiderVector_reserve")]
  public static extern void RiderVector_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_new_RiderVector__SWIG_0")]
  public static extern global::System.IntPtr new_RiderVector__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_new_RiderVector__SWIG_1")]
  public static extern global::System.IntPtr new_RiderVector__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_new_RiderVector__SWIG_2")]
  public static extern global::System.IntPtr new_RiderVector__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_RiderVector_getitemcopy")]
  public static extern global::System.IntPtr RiderVector_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_RiderVector_getitem")]
  public static extern global::System.IntPtr RiderVector_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_RiderVector_setitem")]
  public static extern void RiderVector_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_RiderVector_AddRange")]
  public static extern void RiderVector_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_RiderVector_GetRange")]
  public static extern global::System.IntPtr RiderVector_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_RiderVector_Insert")]
  public static extern void RiderVector_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_RiderVector_InsertRange")]
  public static extern void RiderVector_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_RiderVector_RemoveAt")]
  public static extern void RiderVector_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_RiderVector_RemoveRange")]
  public static extern void RiderVector_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_RiderVector_Repeat")]
  public static extern global::System.IntPtr RiderVector_Repeat(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_RiderVector_Reverse__SWIG_0")]
  public static extern void RiderVector_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_RiderVector_Reverse__SWIG_1")]
  public static extern void RiderVector_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_RiderVector_SetRange")]
  public static extern void RiderVector_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_delete_RiderVector")]
  public static extern void delete_RiderVector(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_IntVector_Clear")]
  public static extern void IntVector_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_IntVector_Add")]
  public static extern void IntVector_Add(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_IntVector_size")]
  public static extern uint IntVector_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_IntVector_capacity")]
  public static extern uint IntVector_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_IntVector_reserve")]
  public static extern void IntVector_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_new_IntVector__SWIG_0")]
  public static extern global::System.IntPtr new_IntVector__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_new_IntVector__SWIG_1")]
  public static extern global::System.IntPtr new_IntVector__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_new_IntVector__SWIG_2")]
  public static extern global::System.IntPtr new_IntVector__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_IntVector_getitemcopy")]
  public static extern int IntVector_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_IntVector_getitem")]
  public static extern int IntVector_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_IntVector_setitem")]
  public static extern void IntVector_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_IntVector_AddRange")]
  public static extern void IntVector_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_IntVector_GetRange")]
  public static extern global::System.IntPtr IntVector_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_IntVector_Insert")]
  public static extern void IntVector_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_IntVector_InsertRange")]
  public static extern void IntVector_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_IntVector_RemoveAt")]
  public static extern void IntVector_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_IntVector_RemoveRange")]
  public static extern void IntVector_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_IntVector_Repeat")]
  public static extern global::System.IntPtr IntVector_Repeat(int jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_IntVector_Reverse__SWIG_0")]
  public static extern void IntVector_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_IntVector_Reverse__SWIG_1")]
  public static extern void IntVector_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_IntVector_SetRange")]
  public static extern void IntVector_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_IntVector_Contains")]
  public static extern bool IntVector_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_IntVector_IndexOf")]
  public static extern int IntVector_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_IntVector_LastIndexOf")]
  public static extern int IntVector_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_IntVector_Remove")]
  public static extern bool IntVector_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_delete_IntVector")]
  public static extern void delete_IntVector(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_OrderVector_Clear")]
  public static extern void OrderVector_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_OrderVector_Add")]
  public static extern void OrderVector_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_OrderVector_size")]
  public static extern uint OrderVector_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_OrderVector_capacity")]
  public static extern uint OrderVector_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_OrderVector_reserve")]
  public static extern void OrderVector_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_new_OrderVector__SWIG_0")]
  public static extern global::System.IntPtr new_OrderVector__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_new_OrderVector__SWIG_1")]
  public static extern global::System.IntPtr new_OrderVector__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_new_OrderVector__SWIG_2")]
  public static extern global::System.IntPtr new_OrderVector__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_OrderVector_getitemcopy")]
  public static extern global::System.IntPtr OrderVector_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_OrderVector_getitem")]
  public static extern global::System.IntPtr OrderVector_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_OrderVector_setitem")]
  public static extern void OrderVector_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_OrderVector_AddRange")]
  public static extern void OrderVector_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_OrderVector_GetRange")]
  public static extern global::System.IntPtr OrderVector_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_OrderVector_Insert")]
  public static extern void OrderVector_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_OrderVector_InsertRange")]
  public static extern void OrderVector_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_OrderVector_RemoveAt")]
  public static extern void OrderVector_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_OrderVector_RemoveRange")]
  public static extern void OrderVector_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_OrderVector_Repeat")]
  public static extern global::System.IntPtr OrderVector_Repeat(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_OrderVector_Reverse__SWIG_0")]
  public static extern void OrderVector_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_OrderVector_Reverse__SWIG_1")]
  public static extern void OrderVector_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_OrderVector_SetRange")]
  public static extern void OrderVector_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_delete_OrderVector")]
  public static extern void delete_OrderVector(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_PointVector_Clear")]
  public static extern void PointVector_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_PointVector_Add")]
  public static extern void PointVector_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_PointVector_size")]
  public static extern uint PointVector_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_PointVector_capacity")]
  public static extern uint PointVector_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_PointVector_reserve")]
  public static extern void PointVector_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_new_PointVector__SWIG_0")]
  public static extern global::System.IntPtr new_PointVector__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_new_PointVector__SWIG_1")]
  public static extern global::System.IntPtr new_PointVector__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_new_PointVector__SWIG_2")]
  public static extern global::System.IntPtr new_PointVector__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_PointVector_getitemcopy")]
  public static extern global::System.IntPtr PointVector_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_PointVector_getitem")]
  public static extern global::System.IntPtr PointVector_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_PointVector_setitem")]
  public static extern void PointVector_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_PointVector_AddRange")]
  public static extern void PointVector_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_PointVector_GetRange")]
  public static extern global::System.IntPtr PointVector_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_PointVector_Insert")]
  public static extern void PointVector_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_PointVector_InsertRange")]
  public static extern void PointVector_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_PointVector_RemoveAt")]
  public static extern void PointVector_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_PointVector_RemoveRange")]
  public static extern void PointVector_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_PointVector_Repeat")]
  public static extern global::System.IntPtr PointVector_Repeat(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_PointVector_Reverse__SWIG_0")]
  public static extern void PointVector_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_PointVector_Reverse__SWIG_1")]
  public static extern void PointVector_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_PointVector_SetRange")]
  public static extern void PointVector_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("delivery_model", EntryPoint="CSharp_delete_PointVector")]
  public static extern void delete_PointVector(global::System.Runtime.InteropServices.HandleRef jarg1);
}
