//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class delivery_model {
  public static int X {
    get {
      int ret = delivery_modelPINVOKE.X_get();
      return ret;
    } 
  }

  public static int Y {
    get {
      int ret = delivery_modelPINVOKE.Y_get();
      return ret;
    } 
  }

  public static int INIT_MONEY {
    get {
      int ret = delivery_modelPINVOKE.INIT_MONEY_get();
      return ret;
    } 
  }

  public static int OUTDATE_TIME {
    get {
      int ret = delivery_modelPINVOKE.OUTDATE_TIME_get();
      return ret;
    } 
  }

  public static int ILLEGAL_TIME {
    get {
      int ret = delivery_modelPINVOKE.ILLEGAL_TIME_get();
      return ret;
    } 
  }

}
