//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Order : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Order(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Order obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Order() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          delivery_modelPINVOKE.delete_Order(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint id {
    get {
      uint ret = delivery_modelPINVOKE.Order_id_get(swigCPtr);
      return ret;
    } 
  }

  public Point restaurant {
    get {
      global::System.IntPtr cPtr = delivery_modelPINVOKE.Order_restaurant_get(swigCPtr);
      Point ret = (cPtr == global::System.IntPtr.Zero) ? null : new Point(cPtr, false);
      return ret;
    } 
  }

  public Point dinner {
    get {
      global::System.IntPtr cPtr = delivery_modelPINVOKE.Order_dinner_get(swigCPtr);
      Point ret = (cPtr == global::System.IntPtr.Zero) ? null : new Point(cPtr, false);
      return ret;
    } 
  }

  public uint time {
    get {
      uint ret = delivery_modelPINVOKE.Order_time_get(swigCPtr);
      return ret;
    } 
  }

  public Order() : this(delivery_modelPINVOKE.new_Order__SWIG_0(), true) {
  }

  public Order(uint id) : this(delivery_modelPINVOKE.new_Order__SWIG_1(id), true) {
  }

  public Order(uint id, Point restaurant, Point dinner, uint time) : this(delivery_modelPINVOKE.new_Order__SWIG_2(id, Point.getCPtr(restaurant), Point.getCPtr(dinner), time), true) {
    if (delivery_modelPINVOKE.SWIGPendingException.Pending) throw delivery_modelPINVOKE.SWIGPendingException.Retrieve();
  }

}
