//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class PointVector : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<Point>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PointVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PointVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PointVector() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          delivery_modelPINVOKE.delete_PointVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public PointVector(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (Point element in c) {
      this.Add(element);
    }
  }

  public PointVector(global::System.Collections.Generic.IEnumerable<Point> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (Point element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public Point this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(Point[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(Point[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, Point[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public Point[] ToArray() {
    Point[] array = new Point[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<Point> global::System.Collections.Generic.IEnumerable<Point>.GetEnumerator() {
    return new PointVectorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new PointVectorEnumerator(this);
  }

  public PointVectorEnumerator GetEnumerator() {
    return new PointVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class PointVectorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<Point>
  {
    private PointVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public PointVectorEnumerator(PointVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public Point Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (Point)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    delivery_modelPINVOKE.PointVector_Clear(swigCPtr);
  }

  public void Add(Point x) {
    delivery_modelPINVOKE.PointVector_Add(swigCPtr, Point.getCPtr(x));
    if (delivery_modelPINVOKE.SWIGPendingException.Pending) throw delivery_modelPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = delivery_modelPINVOKE.PointVector_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = delivery_modelPINVOKE.PointVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    delivery_modelPINVOKE.PointVector_reserve(swigCPtr, n);
  }

  public PointVector() : this(delivery_modelPINVOKE.new_PointVector__SWIG_0(), true) {
  }

  public PointVector(PointVector other) : this(delivery_modelPINVOKE.new_PointVector__SWIG_1(PointVector.getCPtr(other)), true) {
    if (delivery_modelPINVOKE.SWIGPendingException.Pending) throw delivery_modelPINVOKE.SWIGPendingException.Retrieve();
  }

  public PointVector(int capacity) : this(delivery_modelPINVOKE.new_PointVector__SWIG_2(capacity), true) {
    if (delivery_modelPINVOKE.SWIGPendingException.Pending) throw delivery_modelPINVOKE.SWIGPendingException.Retrieve();
  }

  private Point getitemcopy(int index) {
    Point ret = new Point(delivery_modelPINVOKE.PointVector_getitemcopy(swigCPtr, index), true);
    if (delivery_modelPINVOKE.SWIGPendingException.Pending) throw delivery_modelPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private Point getitem(int index) {
    Point ret = new Point(delivery_modelPINVOKE.PointVector_getitem(swigCPtr, index), false);
    if (delivery_modelPINVOKE.SWIGPendingException.Pending) throw delivery_modelPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, Point val) {
    delivery_modelPINVOKE.PointVector_setitem(swigCPtr, index, Point.getCPtr(val));
    if (delivery_modelPINVOKE.SWIGPendingException.Pending) throw delivery_modelPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(PointVector values) {
    delivery_modelPINVOKE.PointVector_AddRange(swigCPtr, PointVector.getCPtr(values));
    if (delivery_modelPINVOKE.SWIGPendingException.Pending) throw delivery_modelPINVOKE.SWIGPendingException.Retrieve();
  }

  public PointVector GetRange(int index, int count) {
    global::System.IntPtr cPtr = delivery_modelPINVOKE.PointVector_GetRange(swigCPtr, index, count);
    PointVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new PointVector(cPtr, true);
    if (delivery_modelPINVOKE.SWIGPendingException.Pending) throw delivery_modelPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, Point x) {
    delivery_modelPINVOKE.PointVector_Insert(swigCPtr, index, Point.getCPtr(x));
    if (delivery_modelPINVOKE.SWIGPendingException.Pending) throw delivery_modelPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, PointVector values) {
    delivery_modelPINVOKE.PointVector_InsertRange(swigCPtr, index, PointVector.getCPtr(values));
    if (delivery_modelPINVOKE.SWIGPendingException.Pending) throw delivery_modelPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    delivery_modelPINVOKE.PointVector_RemoveAt(swigCPtr, index);
    if (delivery_modelPINVOKE.SWIGPendingException.Pending) throw delivery_modelPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    delivery_modelPINVOKE.PointVector_RemoveRange(swigCPtr, index, count);
    if (delivery_modelPINVOKE.SWIGPendingException.Pending) throw delivery_modelPINVOKE.SWIGPendingException.Retrieve();
  }

  public static PointVector Repeat(Point value, int count) {
    global::System.IntPtr cPtr = delivery_modelPINVOKE.PointVector_Repeat(Point.getCPtr(value), count);
    PointVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new PointVector(cPtr, true);
    if (delivery_modelPINVOKE.SWIGPendingException.Pending) throw delivery_modelPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    delivery_modelPINVOKE.PointVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    delivery_modelPINVOKE.PointVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (delivery_modelPINVOKE.SWIGPendingException.Pending) throw delivery_modelPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, PointVector values) {
    delivery_modelPINVOKE.PointVector_SetRange(swigCPtr, index, PointVector.getCPtr(values));
    if (delivery_modelPINVOKE.SWIGPendingException.Pending) throw delivery_modelPINVOKE.SWIGPendingException.Retrieve();
  }

}
